apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-custom
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: hello-k8s-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-k8s-custom
  template:
    metadata:
      labels:
        app: hello-k8s-custom
    spec:
      containers:
      - name: hello-k8s
        image: ahaliulov/hello-k8s:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: This is my custom message from hello-k8s app.